[package]
name = "file-format"
version = "0.9.1"
authors = ["Mickaël Malécot <mickael.malecot@gmail.com>"]
edition = "2021"
description = "Crate for determining binary-based file formats."
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["file-format", "file-type", "magic-number", "media-type", "mime"]
homepage = "https://github.com/mmalecot/file-format"
repository = "https://github.com/mmalecot/file-format"
documentation = "https://docs.rs/file-format"
exclude = ["/.github/*", "/fixtures/*", "/tests/*", "/examples/*"]

[dependencies]
cfb = { version = "0.7", optional = true }
zip = { version = "0.6", optional = true, features = ["deflate-miniz"], default-features = false }

[dev-dependencies]
clap = { version = "4.0", features = ["derive"] }
colored = { version = "2.0" }

[features]
cfb = ["dep:cfb"]
zip = ["dep:zip"]
