[package]
name = "file-format"
version = "0.11.0"
authors = ["Mickaël Malécot <mickael.malecot@gmail.com>"]
edition = "2021"
description = "Crate for determining file formats."
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["file-format", "file-type", "magic-number", "media-type", "mime"]
categories = ["filesystem"]
homepage = "https://github.com/mmalecot/file-format"
repository = "https://github.com/mmalecot/file-format"
documentation = "https://docs.rs/file-format"
exclude = ["/.github/*", "/examples/*", "/fixtures/*", "/tests/*"]

[dependencies]
cfb = { version = "0.7", optional = true }
zip = { version = "0.6", optional = true, features = ["deflate-miniz"], default-features = false }

[features]
cfb = ["dep:cfb"]
zip = ["dep:zip"]
